/**
 * Minimal end-to-end example using the in-memory adapter — no database
 * required. Run with: npx tsx examples/basic.ts
 *
 * This adapter is for local development, tests, and prototyping only (see
 * README "Which adapter should I use?"). For anything real, use the
 * PostgreSQL adapter — see examples/postgres/.
 */
import { MemoryKujiEngine } from '../src/adapters/memory';

async function main() {
  const engine = new MemoryKujiEngine();

  // 1. Configure the box: prize ids and quantities only. The engine computes
  //    a cryptographically-secure, quantity-preserving random assignment —
  //    there is no seed, weight, or "forced prize" parameter anywhere.
  await engine.createBox({
    id: 'chiikawa-kuji-001',
    prizes: [
      { id: 'S-tier-figure', quantity: 1 },
      { id: 'A-tier-plush', quantity: 3 },
      { id: 'B-tier-keychain', quantity: 6 },
      { id: 'C-tier-sticker', quantity: 10 },
    ],
    lastOnePrizeId: 'A-tier-plush', // awarded once, to whoever draws the final normal ticket
  });

  // 2. Open it for sale.
  await engine.openBox('chiikawa-kuji-001');

  // 3. A customer picks ticket numbers and draws. `requestId` should be
  //    generated by your server per attempt (e.g. a UUID) so retries are
  //    safe: the same requestId + same input replays the same result
  //    instead of drawing twice.
  const result = await engine.draw('chiikawa-kuji-001', {
    requestId: 'req-abc123',
    holder: 'user-42', // an id YOUR system has already authenticated
    ticketNos: [7, 8],
  });
  console.log('Draw result:', result);

  // 4. Public state for rendering a "remaining tickets" screen. This never
  //    includes which prize an undrawn ticket holds.
  const publicView = await engine.getPublicBox('chiikawa-kuji-001');
  console.log('Public view:', publicView);

  // 5. Retrying the exact same request is safe and returns the same result
  //    (no second draw happens).
  const replay = await engine.draw('chiikawa-kuji-001', {
    requestId: 'req-abc123',
    holder: 'user-42',
    ticketNos: [7, 8],
  });
  console.log('Replay === original:', JSON.stringify(replay) === JSON.stringify(result));
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
